name: test Build and Push Docker Image to GitHub Packages

on: workflow_dispatch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/caddy-cf
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]') # Ensure lowercase
          docker build -t $IMAGE_NAME:latest ./caddy/cf
          docker push $IMAGE_NAME:latest
